### ISSUE TITLE
Can VisTR be applied to the task of semantic segmentation of video objects?

### ISSUE THREAD

**Issue by longmalongma** [Epiphqny/VisTR#1]
Thank you very much for your great work. I have followed you. Can VisTR be applied to the task of video objects semantic segmentation? What changes do we need to make when migrating your network to the task of video objects semantic segmentation? looking forward to your reply.

**Comment by Epiphqny** [comment]
@longmalongma The predictions are based on instance queries. If you want to perform semantic segmentation, you should represent each mask as an object with the largest bounding box as the whole image size. Just like what DETR does for panoptic segmentation.

**Comment by longmalongma** [comment]
> @longmalongma The predictions are based on instance queries. If you want to perform semantic segmentation, you should represent each mask as an object with the largest bounding box as the whole image size. Just like what DETR does for panoptic segmentation.

Thanks for your reply. Are there many changes that need to be made?

**Comment by Epiphqny** [comment]
@longmalongma I think there are many changes, besides, if the number of the objects for semantic segmentation is large, the memory will be a big issue. 

I think I've answered your question and as such I'm closing this issue, but let us know if you have further questions

**Comment by longmalongma** [comment]
> @longmalongma I think there are many changes, besides, if the number of the objects for semantic segmentation is large, the memory will be a big issue.
> 
> I think I've answered your question and as such I'm closing this issue, but let us know if you have further questions

ok, thank you very much.
