### ISSUE TITLE
About GPU memory

### ISSUE THREAD

**Issue by y6216886** [Epiphqny/VisTR#10]
Thank you for your inspiring work.
As you mentioned in readme, the required GPU memory is at least 32GB,  which is inapplicable for many researchers. 
In this way, I have a question.
Is it possible to train ``visTR'' in 3*TITAN X GPU with 12GB memory each?

**Comment by Epiphqny** [comment]
Hi @y6216886, It will be hard for the network to train on such cards as the memory is too small to process 36 image frames directly.

**Comment by swrdZWJ** [comment]
I have the same question. Is it possible to train in 4*3090 GPU with 24GB memory, and how many GPU resources did you take during the training process under different setting？
