### ISSUE TITLE
Long training time

### ISSUE THREAD

**Issue by jasminezz** [Epiphqny/VisTR#12]
using 4 V100,32G to train the model, about 1day for 1 epoch.how can i improve the speed from the algorithm?

**Comment by Epiphqny** [comment]
Hi @jasminezz, it takes about 7-8 hours to train 1 epoch on 8 v100. As both processing multiple frames in one model and training transformers are time-consuming. Besides, the original DETR model for training segmentation is also slow. We have no idea to speed up the training at this time, in the future it may be solved by a more efficient transformer model. But the model has good performance even only training for 1 epoch. You could test and use a small epoch number for the experiment.
