### ISSUE TITLE
Question about instance queries

### ISSUE THREAD

**Issue by Kris-cong** [Epiphqny/VisTR#13]
Thank you for sharing this great work! I have a question about the instance queries. Are instance categories and instance queries arranged in order? In other words, Whether the final output category of the first instance queries in the frame 1 and the first instance queries in the frame 2 is the same ? If they're  same，how to do that? (I can't find description of this in the paper)  Thank you!

**Comment by Epiphqny** [comment]
@Kris-cong We didn't constrain the category of the same instance in different frames, but the ground truth of the same instance is the same, therefore it is only learned by supervision. In the Inference section of 4.1 of the paper, we said,"For instances that have been classified to different categories in different frames, we use the most frequently predicted category as the final instance category".
