### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'VisTRsegm' object has no attribute 'module'

### ISSUE THREAD

**Issue by PipiZong** [Epiphqny/VisTR#14]
Hi, Thanks for sharing your great work! 
When I run python main.py --pretrained_weights 384_coco_r50.pth --backbone resnet50 --num_frames 2 --mask on one GPU ( I only have one), this error appears in the line model.module.load_state_dict(checkpoint, strict=False). This checkpoint was downloaded from your drive named '384_coco_r50.pth', could you please help fix this? And could you share one demo video sample data so we can reproduce this code more easily?  Thanks!

**Comment by Epiphqny** [comment]
Hi @PipiZong, it is because the code is written for multiple GPUs, you could try to modify the torch.nn.DataParallel code to one gpu setting to see if it works, we have not tried one GPU setting.
