### ISSUE TITLE
请问可以利用此方法进行RGB->Seg语义分割预测吗？

### ISSUE THREAD

**Issue by bugsuse** [Epiphqny/VisTR#15]
非常感谢开源！我是气象专业的学生，大概看了论文的内容，文中提到了知道 `t-n, ..., t-1, t, t+1, ..., t+n` 序列的视频帧，其中 t 时刻已经标注，可以利用 t 时刻前后信息来进行分割。

因此，我想请问一下此模型是否可以只利用 t 时刻之前的视频帧预测分割t时刻的视频帧呢？类似已知 t 时刻的雷达回波和不同类型对流的标注图像，训练监督学习模型，然后利用一系列雷达回波预测分割未来某一时刻雷达图像的对流类型？

**Comment by Epiphqny** [comment]
@bugsuse You could modify the supervision and try it.
