### ISSUE TITLE
How long does one epoch training take

### ISSUE THREAD

**Issue by chrisjuniorli** [Epiphqny/VisTR#18]
I wonder how long does one epoch training take if you use 8xV100 GPUs, 
I am using 4xV100 GPUs and it takes ~20 hours for one epoch, so it's like 10 hours per epoch for 8xV100?

**Comment by Epiphqny** [comment]
Hi @chrisjuniorli Please refer to https://github.com/Epiphqny/VisTR/issues/12

**Comment by chrisjuniorli** [comment]
Thanks for replying, it solves my problem
