### ISSUE TITLE
Why input size is d × (T · H · W )  ?

### ISSUE THREAD

**Issue by WinstonDeng** [Epiphqny/VisTR#19]
Some questions:
1. In Section 3.1, you use d × (T · H · W ) as input size. Why not  T × (d · H · W )?  
2. CNN feature is reshaped to B×C×THW. However, the input token size is HW × B  × C  for transformer encoder in code. It seems confusing.

**Comment by Epiphqny** [comment]
hi @WinstonDeng 

1. The d is the number of the feature dimension, we want to take the whole video as a whole, i.e., the spatial and temporal features should be flattened together to 1 dimension, therefore we use d × (T · H · W ).
2. Don't know what you mean by "input token size is HW × B × C". As we modified our 3D feature to suit the 2D version of transformer code, the names in the transformer encoder are confusing, please ignore it.

**Comment by WinstonDeng** [comment]
@Epiphqny, great thanks for your reply! 

**For question1:**
The reason why I'm confused is that the transformer model in DETR  seems to be different from the traditional seq2seq transformer. 

In seq2seq model, input for encoder is (B,Encode_Seq_Len,C),  and input for decoder is (B,Decode_Seq_Len,C) when training. 
Thus, taking the encoder for an example, Multihead-Attention captures relationships between input seq items. Following this theory, T × (d · H · W ) is an intuitive idea instead of d × (T · H · W ). 

Another difference is that DETR and VisTR use non-autoregress schema for decoding stage, so that you can predict all results directly. 
I'm not clear about the reasons. 

**For question2:**
In models/transformer.py, line 47
```
def forward(self, src, mask, query_embed, pos_embed):
        # flatten NxCxHxW to HWxNxC
        bs, c, h, w = src.shape
        src = src.flatten(2).permute(2, 0, 1)
        pos_embed = pos_embed.flatten(2).permute(2, 0, 1)
        query_embed = query_embed.unsqueeze(1).repeat(1, bs, 1)
        mask = mask.flatten(1)

        tgt = torch.zeros_like(query_embed)
        memory = self.encoder(src, src_key_padding_mask=mask, pos=pos_embed)
        hs = self.decoder(tgt, memory, memory_key_padding_mask=mask,
                          pos=pos_embed, query_pos=query_embed)
        return hs.transpose(1, 2), memory.permute(1, 2, 0).view(bs, c, h, w)
```

**Comment by Epiphqny** [comment]
@WinstonDeng For question2 , As shown in https://github.com/Epiphqny/VisTR/blob/cfa6fa9391338ae8ef7365b40ee06777a9d41e95/models/segmentation.py#L93, the dimension of h and w has already been flattened to suit the transformer, therefore the HW of transformer code is not the real h w.

**Comment by WinstonDeng** [comment]
I got it.
The attention map size is thw*thw according to your config, thus you can model spatial-temporal interactions.
Thanks again!
