### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools.ytvos'

### ISSUE THREAD

**Issue by qslia** [Epiphqny/VisTR#20]
i have done this 

git clone https://github.com/youtubevos/cocoapi.git

cd PythonAPI

python setup.py build_ext --inplace

python setup.py build_ext install

still  No module named 'pycocotools.ytvos' 

pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
pip install git+https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"

Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/cocodataset/cocoapi.git to /tmp/pip-req-build-x2a4p4jp
  Running command git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-x2a4p4jp
  fatal: unable to access 'https://github.com/cocodataset/cocoapi.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
WARNING: Discarding git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI. Command errored out with exit status 128: git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-x2a4p4jp Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-x2a4p4jp Check the logs for full command output.

**Comment by Epiphqny** [comment]
hi @qslia Please refer to https://github.com/Epiphqny/VisTR/issues/5#issuecomment-802628042

**Comment by qslia** [comment]
> hi @qslia Please refer to [#5 (comment)](https://github.com/Epiphqny/VisTR/issues/5#issuecomment-802628042)

i have saw it, what is 'If there is still problem, you could try to directly copy the built pycocotools of ytvos to your python installation path.' full meaning? can you tell more detals, where is the built pycocotools.

**Comment by ttlmh** [comment]
> > hi @qslia Please refer to [#5 (comment)](https://github.com/Epiphqny/VisTR/issues/5#issuecomment-802628042)
> 
> i have saw it, what is 'If there is still problem, you could try to directly copy the built pycocotools of ytvos to your python installation path.' full meaning? can you tell more detals, where is the built pycocotools.

Run 'pip install -U git+https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"'

**Comment by qslia** [comment]
> > > hi @qslia Please refer to [#5 (comment)](https://github.com/Epiphqny/VisTR/issues/5#issuecomment-802628042)
> > 
> > 
> > i have saw it, what is 'If there is still problem, you could try to directly copy the built pycocotools of ytvos to your python installation path.' full meaning? can you tell more detals, where is the built pycocotools.
> 
> Run 'pip install -U git+[https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI](https://github.com/youtubevos/cocoapi.git#%22egg=pycocotools&subdirectory=PythonAPI)"'


base) root@iZ8vb4fe2fj7uy9gqp0tipZ:~/VisTR# python inference.py --masks --model_path 384_coco_r101.pth 
Traceback (most recent call last):
  File "inference.py", line 16, in <module>
    import datasets
  File "/root/VisTR/datasets/__init__.py", line 5, in <module>
    from .ytvos import build as build_ytvos
  File "/root/VisTR/datasets/ytvos.py", line 9, in <module>
    from pycocotools.ytvos import YTVOS
ModuleNotFoundError: No module named 'pycocotools.ytvos'

is this command correct for inference?

**Comment by Epiphqny** [comment]
@qslia You should know your python package installation path and copy the built folder to the package path.

**Comment by amobiny** [comment]
It seems like the youtubevos cocoapi does not get properly set up for some people.
I actually found a way to solve this problem according to @Epiphqny 's comment and I'll write the details here.
I just copied the ytvos.py and ytvoseval.py files (you can find them [here](https://github.com/youtubevos/cocoapi/tree/master/PythonAPI/pycocotools)) to the right directory in the Python site-packages. For example, if you are using a conda environment named visTR and python 3.7, the directory to copy into will be something like ./anaconda3/envs/visTR/lib/python3.7/site-packages/pycocotools.

**Comment by cuizoe-github** [comment]
> i have done this
> 
> git clone https://github.com/youtubevos/cocoapi.git
> 
> cd PythonAPI
> 
> python setup.py build_ext --inplace
> 
> python setup.py build_ext install
> 
> still No module named 'pycocotools.ytvos'
> 
> pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI' pip install git+[https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI](https://github.com/youtubevos/cocoapi.git#%22egg=pycocotools&subdirectory=PythonAPI)"
> 
> Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple, https://pypi.ngc.nvidia.com Collecting git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI Cloning https://github.com/cocodataset/cocoapi.git to /tmp/pip-req-build-x2a4p4jp Running command git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-x2a4p4jp fatal: unable to access 'https://github.com/cocodataset/cocoapi.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated. WARNING: Discarding git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI. Command errored out with exit status 128: git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-x2a4p4jp Check the logs for full command output. ERROR: Command errored out with exit status 128: git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-x2a4p4jp Check the logs for full command output.

I have the same problem as you, but I can't solve it after trying many methods. Have you solved this problem？
