### ISSUE TITLE
About visualization of results

### ISSUE THREAD

**Issue by superXR** [Epiphqny/VisTR#21]
I would like to know how to convert the results.json into a visual video or image，could you give some code reference?

**Comment by Epiphqny** [comment]
Hi @superXR, we have no plan to release the visual code, you could implement it by yourself. Thanks!

**Comment by qzsrh** [comment]
> I would like to know how to convert the results.json into a visual video or image，could you give some code reference?
Hello! Have you addressed it? I met the same problem.
