### ISSUE TITLE
python inference.py --masks --model_path vistr_r50.pth

### ISSUE THREAD

**Issue by qslia** [Epiphqny/VisTR#22]
File "inference.py", line 236, in <module>
    main(args)
  File "inference.py", line 172, in main
    model.load_state_dict(state_dict)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisTRsegm:
	Missing key(s) in state_dict: "vistr.backbone.0.body.layer3.6.conv1.weight",

**Comment by qslia** [comment]
File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisTRsegm:
	Missing key(s) in state_dict: "mask_head.conv_offset.weight", "mask_head.conv_offset.bias", "mask_head.dcn.weight", "insmask_head.0.weight", "insmask_head.0.bias", "insmask_head.1.weight", "insmask_head.1.bias", "insmask_head.3.weight", "insmask_head.3.bias", "insmask_head.4.weight", "insmask_head.4.bias", "insmask_head.6.weight", "insmask_head.6.bias", "insmask_head.7.weight", "insmask_head.7.bias", "insmask_head.9.weight", "insmask_head.9.bias". 
	Unexpected key(s) in state_dict: "mask_head.lay5.weight", "mask_head.lay5.bias", "mask_head.out_lay.weight", "mask_head.out_lay.bias". 
	size mismatch for vistr.class_embed.weight: copying a param with shape torch.Size([92, 384]) from checkpoint, the shape in current model is torch.Size([41, 384]).
	size mismatch for vistr.class_embed.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([41]).
	size mismatch for vistr.query_embed.weight: copying a param with shape torch.Size([100, 384]) from checkpoint, the shape in current model is torch.Size([360, 384]).

**Comment by qslia** [comment]
(base) root@iZ8vb4fe2fj7uy9gqp0tipZ:~/VisTR# python inference.py --masks --model_path 384_coco_r101.pth 
Traceback (most recent call last):
  File "inference.py", line 236, in <module>
    main(args)
  File "inference.py", line 172, in main
    model.load_state_dict(state_dict)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisTRsegm:
	Missing key(s) in state_dict: "mask_head.conv_offset.weight", "mask_head.conv_offset.bias", "mask_head.dcn.weight", "insmask_head.0.weight", "insmask_head.0.bias", "insmask_head.1.weight", "insmask_head.1.bias", "insmask_head.3.weight", "insmask_head.3.bias", "insmask_head.4.weight", "insmask_head.4.bias", "insmask_head.6.weight", "insmask_head.6.bias", "insmask_head.7.weight", "insmask_head.7.bias", "insmask_head.9.weight", "insmask_head.9.bias". 
	Unexpected key(s) in state_dict: "mask_head.lay5.weight", "mask_head.lay5.bias", "mask_head.out_lay.weight", "mask_head.out_lay.bias". 
	size mismatch for vistr.class_embed.weight: copying a param with shape torch.Size([92, 384]) from checkpoint, the shape in current model is torch.Size([41, 384]).
	size mismatch for vistr.class_embed.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([41]).
	size mismatch for vistr.query_embed.weight: copying a param with shape torch.Size([100, 384]) from checkpoint, the shape in current model is torch.Size([360, 384]).
(base) root@iZ8vb4fe2fj7uy9gqp0tipZ:~/VisTR#

**Comment by qslia** [comment]
File "inference.py", line 236, in <module>
    main(args)
  File "inference.py", line 172, in main
    model.load_state_dict(state_dict)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisTRsegm:
	Missing key(s) in state_dict: "mask_head.conv_offset.weight", "mask_head.conv_offset.bias", "mask_head.dcn.weight", "insmask_head.0.weight", "insmask_head.0.bias", "insmask_head.1.weight", "insmask_head.1.bias", "insmask_head.3.weight", "insmask_head.3.bias", "insmask_head.4.weight", "insmask_head.4.bias", "insmask_head.6.weight", "insmask_head.6.bias", "insmask_head.7.weight", "insmask_head.7.bias", "insmask_head.9.weight", "insmask_head.9.bias". 
	Unexpected key(s) in state_dict: "mask_head.lay5.weight", "mask_head.lay5.bias", "mask_head.out_lay.weight", "mask_head.out_lay.bias". 
	size mismatch for vistr.class_embed.weight: copying a param with shape torch.Size([92, 384]) from checkpoint, the shape in current model is torch.Size([41, 384]).
	size mismatch for vistr.class_embed.bias: copying a param with shape torch.Size([92]) from checkpoint, the shape in current model is torch.Size([41]).
	size mismatch for vistr.query_embed.weight: copying a param with shape torch.Size([100, 384]) from checkpoint, the shape in current model is torch.Size([360, 384]).

**Comment by qslia** [comment]
it seems  something wrong with 384_coco_r101.pth vistr_r50.pth

**Comment by qslia** [comment]
when i using vistr_r101.pth

Process video:  0
/root/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py:3118: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
Process video:  1
Process video:  2
Process video:  3

it seems working all right

**Comment by XD7479** [comment]
I met the same problem both when using the provided _vistr_r50.pth_ and which trained from _384_coco_r50.pth_ by myself.

_vistr_r101.pth_ is working all right, 
but when I try to train one based on _384_coco_r101.pth_, it always says 'CUDA out of memory'. I'm using 8 32G Tesla V100.

**Comment by XD7479** [comment]
> I met the same problem both when using the provided _vistr_r50.pth_ and which trained from _384_coco_r50.pth_ by myself.
> 
> _vistr_r101.pth_ is working all right,
> but when I try to train one based on _384_coco_r101.pth_, it always says 'CUDA out of memory'. I'm using 8 32G Tesla V100.

Fixed. Add '--backbone resnet50' while running inference.

**Comment by rambleramble** [comment]
@XD7479 
I have encountered the same issue as

> but when I try to train one based on 384_coco_r101.pth, it always says 'CUDA out of memory'. I'm using 8 32G Tesla V100.

Did you solve it?
