### ISSUE TITLE
category_id

### ISSUE THREAD

**Issue by CuckooHXY** [Epiphqny/VisTR#25]
I notice that your category_id is from 0 to 39,while masktrackrcnn is from 1 to 40.It confuses me.
I inference the validation set with the weight you trained,and delete all the results with "category_id"=0  in the results.json.But the score doesn't change.Could you please tell me why?

**Comment by Epiphqny** [comment]
Hi @CuckooHXY, this is the same issue as https://github.com/Epiphqny/VisTR/issues/11, I am fixing this bug, and the result improves. I will update the code and result later.

**Comment by Epiphqny** [comment]
Hi @CuckooHXY, I have fixed the bug and updated the code and result.
