### ISSUE TITLE
The youtubevis valid dataset

### ISSUE THREAD

**Issue by sally1913105** [Epiphqny/VisTR#26]
I wanted to test the results of your model, but I found that there was no segmentation information in the label of YouTubevis's Valid dataset

**Comment by sally1913105** [comment]
Did you combine the Valid label.json file with the Valid result.json file

**Comment by Epiphqny** [comment]
hi @sally1913105 , there is no ground truth for valid dataset, it is used as the test-dev to test the performance.

**Comment by sally1913105** [comment]
Thank you for your answer.  Do you split the train data as the  valid dataset ?  how can I to test your model 
![image](https://user-images.githubusercontent.com/56918790/115493665-b6c3a000-a296-11eb-895a-aafa330def13.png) to Verify the accuracy

**Comment by Epiphqny** [comment]
@sally1913105 As described in README, "by submitting the result json file to the CodeLab system"

**Comment by sally1913105** [comment]
ok I get it
