### ISSUE TITLE
The default training params are different between paper and code.

### ISSUE THREAD

**Issue by zzzzzz0407** [Epiphqny/VisTR#27]
![image](https://user-images.githubusercontent.com/27133144/115979385-36fc4500-a5b8-11eb-9037-040cc60eae5f.png)
![image](https://user-images.githubusercontent.com/27133144/115979389-3d8abc80-a5b8-11eb-9e04-df0497376b51.png)
For example lr_backbone in paper 1e-4 and in code 1e-5; epoch 10 in paper and in code 18, if we should adjust it as paper or just use the default params to reproduce the results?

**Comment by Epiphqny** [comment]
Hi @zzzzzz0407, please follow the default params. We will update the paper.

**Comment by zzzzzz0407** [comment]
@Epiphqny Thanks for your quick reply. And I notice that you change the num_class from 40 to 41 recently, it is confused as the background_id is already +1 in code https://github.com/Epiphqny/VisTR/blob/master/models/vistr.py#L39

**Comment by Epiphqny** [comment]
@zzzzzz0407 Following the same practice in https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/models/detr.py#L305, the num_class corresponds to `max_obj_id + 1`, the max_obj_id for VIS is 40. Actually, there are two id indexes for background, the id of 0 is used to represent empty box (for box that disappears in some frame) in https://github.com/Epiphqny/VisTR/blob/3f736292330424f53905bdcfb1cdf07cc2902eb5/datasets/ytvos.py#L108, and the 41 is used to represent the background.

**Comment by zzzzzz0407** [comment]
@Epiphqny Okay, I get it.
