### ISSUE TITLE
For training time

### ISSUE THREAD

**Issue by midsdsy** [Epiphqny/VisTR#28]
Thank you for your work.
I try to re-train the code, but it takes a week for 18 epochs with ResNet-50 backbone on 8 V100 GPUs . Does it need to be trained so long? As far as I know, it just takes several days for training DETR with 300 epochs.

**Comment by Epiphqny** [comment]
Hi @midsdsy, the detr with segmentation training is also slow. More details please follow https://github.com/Epiphqny/VisTR/issues/12

**Comment by midsdsy** [comment]
Thank you!
