### ISSUE TITLE
category_id

### ISSUE THREAD

**Issue by CuckooHXY** [Epiphqny/VisTR#29]
Thanks a lot for your work.Now your model outputs 42 labels,i.e.0-41,and you select 0-40.Since 1-40 is categories in  the annotation,does 0 mean background?And what does 41 mean?

**Comment by Epiphqny** [comment]
Hi @CuckooHXY, please refer to the answer in https://github.com/Epiphqny/VisTR/issues/27#issuecomment-826291313
