### ISSUE TITLE
Can your model be used for semi-supervised video object segmentation? 

### ISSUE THREAD

**Issue by longmalongma** [Epiphqny/VisTR#31]
Can your model be used for semi-supervised video object segmentation? What changes need to be made?

**Comment by Epiphqny** [comment]
Hi @longmalongma, we actually provide a pipeline for video tasks, you could modify the input and supervision for your task. I haven't tried this task, you could have a try.

**Comment by longmalongma** [comment]
> we actually provide a pipeline for video tasks, you could modify the input and supervision for your task. I haven't tried this task, you could have a try.

Ok, thanks!
