### ISSUE TITLE
about position embedding

### ISSUE THREAD

**Issue by longmalongma** [Epiphqny/VisTR#32]
![image](https://user-images.githubusercontent.com/40291722/116672016-3c9cc500-a9d4-11eb-8657-f53262504e27.png)

Are the position coded inputs and outputs tensor?What are the dimensions of the input and output of position coding?

**Comment by Epiphqny** [comment]
Hi @longmalongma, the position encoding encodes the x,y,z indexes into features, the feature dimension is the same as the dimension of the transformer feature dimension to be added to it. Please read the paper for more details.
