### ISSUE TITLE
bbox and mask

### ISSUE THREAD

**Issue by CuckooHXY** [Epiphqny/VisTR#38]
I try to visualize the predictions,and find mask is not wholely in bounding box.Should it be like that?Or is my visualization wrong?
![0](https://user-images.githubusercontent.com/74082058/118444502-c8765700-b71f-11eb-9070-9164e7ccd932.png)

**Comment by Epiphqny** [comment]
Hi @CuckooHXY, the visualization is right, the mask is globally predicted, therefore we didn't constrain the area to be in the box.

**Comment by OfryZarfaty** [comment]
> I try to visualize the predictions,and find mask is not wholely in bounding box.Should it be like that?Or is my visualization wrong? ![0](https://user-images.githubusercontent.com/74082058/118444502-c8765700-b71f-11eb-9070-9164e7ccd932.png)

Hi, can you refer how to visualize the results.json?

**Comment by YuqingWang1029** [comment]
Hi @OfryZarfaty, The visualization is correct, the mask is not constrained by the box area.

**Comment by matan2455** [comment]
Hey @CuckooHXY, 
How did you manage to visualize the results? 
I ran the model on a new video and got RLE format masks for it, just couldn't find any guide on how to visualize the results.
