### ISSUE TITLE
Inference with Tracking

### ISSUE THREAD

**Issue by priya-dwivedi** [Epiphqny/VisTR#4]
@Epiphqny - Excellent work. We would like to test this out for instance segmentation and tracking. Your inference.py file says that this code does video segmentation only, no tracking. The code also seems to be similar to the code used by DETR for segmentation. 
How do we do instance tracking along with segmentation? Could you please share thoughts or code for that.

**Comment by Epiphqny** [comment]
Hi@priya-dwivedi, thanks for your interest in our work. If the video is not larger than 36 frames, the tracking could be naturally realized with this code. If the frame number is larger than our default frame number, you could refer this https://github.com/Epiphqny/VisTR/issues/3
