### ISSUE TITLE
about instances_train_sub.json of dataset

### ISSUE THREAD

**Issue by wenchen4321** [Epiphqny/VisTR#41]
Thanks for interesting works. I have a question about the dataset. I download the label of the dataset which has "train.json" but not instances_train_sub.json. Where can I download the sub json?

**Comment by anna-debug** [comment]
They are the same, just rename the the "train.json"

**Comment by d12306** [comment]
@Epiphqny , i believe these are the splits that you create for tuning hyperparamters. Would you mind share this file with us?
