### ISSUE TITLE
About the results  and the loss convergence

### ISSUE THREAD

**Issue by cqg1997** [Epiphqny/VisTR#46]
I run your code in 8 V100 GPUs using resnet50 as backbone. But it seems that the loss convergence is unstable in training after the first few epochs. The AP of the last epoch is 0.33, but the AP of the 12th epoch is 0.35.
Could you provide  the loss curve and the APs of every epoch?  It would be very helpful for me as a reference.
Thanks.

**Comment by YuqingWang1029** [comment]
@cqg1997 The training of transformer is unstable, it is natural. Sorry I have not saved the log and have no card to train it now.
