### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools.ytvos'

### ISSUE THREAD

**Issue by CuberrChen** [Epiphqny/VisTR#5]
hi！I successfully executed the instructions include in “Install pycocotools” part，but when I perform inference, the above problem occurs. I tried to solve it, but it didn't work. I hope to get your help！

**Comment by Epiphqny** [comment]
hi @CuberrChen, you also need to install the ytvos version pycocotools, as mentioned in README.

**Comment by CuberrChen** [comment]
`from pycocotools.ytvos import YTVOS
from pycocotools.ytvoseval import YTVOSeval
import datasets.transforms as T
from pycocotools import mask as coco_mask`

There is an error in the first two sentences, but there is no problem in the last sentence.

**Comment by Epiphqny** [comment]
@CuberrChen That is because you only installed coco version of pycocotools, as mentioned in README, you need to install both the coco and ytvos version of pycocotools.

**Comment by CuberrChen** [comment]
I think so too, but I have successfully implemented the installation instructions in README.md. emm..I'll try again. thanks！

**Comment by Epiphqny** [comment]
@CuberrChen If there is still problem, you could try to directly copy the built pycocotools of ytvos to your python installation path.

**Comment by qslia** [comment]
> @CuberrChen If there is still problem, you could try to directly copy the built pycocotools of ytvos to your python installation path.

where to find the built pycocotols of ytvos, i'm also encounter this problem, and when i execute 
pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
pip install git+https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"
this two command, there always failed installing, and some times can install successfully

**Comment by amobiny** [comment]
@CuberrChen 
I have the same problem.
Were you able to solve this issue?

**Comment by AnaRhisT94** [comment]
> Don't use pip install pycocotools. please install pycocotools locally .https://github.com/youtubevos/cocoapi

This doesn't work.

**Comment by theRain0450** [comment]
> It seems like the youtubevos cocoapi does not get properly set up for some people. I actually found a way to solve this problem according to @Epiphqny 's comment and I'll write the details here. I just copied the ytvos.py and ytvoseval.py files (you can find them [here](https://github.com/youtubevos/cocoapi/tree/master/PythonAPI/pycocotools)) to the right directory in the Python site-packages. For example, if you are using a conda environment named visTR and python 3.7, the directory to copy into will be something like ./anaconda3/envs/visTR/lib/python3.7/site-packages/pycocotools.

I tried this method and successfully solved the error, great!Thanks bro！
