### ISSUE TITLE
Evaluation on released R101 model is slightly worse than reported AP

### ISSUE THREAD

**Issue by bowenc0221** [Epiphqny/VisTR#52]
Hi,

Thanks for sharing the code for VisTR.

I tried to run inference on the R101 model with the given command: `python inference.py --masks --model_path /path/to/model_weights --save_path /path/to/results.json`. But I only got 39.7 AP instead of 40.1 AP.

Any idea why it is 0.4 worse?

<img width="527" alt="Screen Shot 2021-07-08 at 9 54 10 PM" src="https://user-images.githubusercontent.com/25308473/125016468-082e3080-e037-11eb-8517-6fea11f6fb0f.png">

**Comment by rambleramble** [comment]
@bowenc0221  How to obtain this evaluation result? 
Authors mentioned submit the result json file to the CodeLab system, but not very clear on how to. Could you share steps?  
Thanks in advance!!
