### ISSUE TITLE
I cound't find the instances_val_train_sun.json file in codalab page

### ISSUE THREAD

**Issue by StiphyJay** [Epiphqny/VisTR#57]
Thanks for your open-source code. Ii is very helpful for my research. But when i want to train the model, i find i counldn't find the corresponding file instance_train_sub.json' or 'instance__val_sub.json' in the Codalab page(https://competitions.codalab.org/competitions/20128#participate-get_data). I only download the image data.But, for annotation file, I just got the test.json or val.json or train.json file. And in those json file, I couldn't fine the annotation information.I would appreciate it if you could help me to correct this problem.

**Comment by YuqingWang1029** [comment]
Hi @StiphyJay , they are the same as the val.json and train.json file.

**Comment by StiphyJay** [comment]
OK. Got it. Thank you!

**Comment by StiphyJay** [comment]
> Hi @StiphyJay , they are the same as the val.json and train.json file.

But when i run the ytvos.py, the YTVOSDataset.__getitem__() only return img, the target didn;t contatin the annotation information. And i find the label file(.json file), there are no annotation information.

**Comment by VJJJJJJ1** [comment]
> 感谢您的开源代码。ii对我的研究很有帮助。但是当我想训练模型时，我发现在 Codalab 页面（[https://competitions.codalab.org/competitions/20128#participate-获取数据](https://competitions.codalab.org/competitions/20128#participate-get_data)）。我只下载图像数据。但是，对于注释文件，我只得到了 test.json 或 val.json 或 train.json 文件。在那些json文件中，我无法细化注释信息。如果你能帮助我纠正这个问题，我将不胜感激。

which one have you downloaded? vis or vos
