### ISSUE TITLE
pretrained Detr weights

### ISSUE THREAD

**Issue by helq2612** [Epiphqny/VisTR#58]
Hi,

Thank you for your great work!
Do you pre-train the Detr weights by yourself? Because I find the official Detr hidden_dim is 256, not 384. If so, do you train it with the object detection task, or the panoptic task?

**Comment by YuqingWang1029** [comment]
Hi @helq2612 I trained with the instance segmentation task, with the hidden_dim being 384.

**Comment by helq2612** [comment]
Thank you very much!
