### ISSUE TITLE
CUDA out of memory on 8xv100 32G  GPUs for r101 training

### ISSUE THREAD

**Issue by rambleramble** [Epiphqny/VisTR#59]
CUDA out of memory with the current source code on 8xv100 32G 

However, it seems the following code, need to use r101 resolution, instead of r50 to fit into 32G of V100.
https://github.com/Epiphqny/VisTR/blob/554e711602dff135b15afb36da0efec46e13f648/datasets/ytvos.py#L167

My question is that the claimed result of r101, is it achieved under the r101 resolution, aka
`                   T.RandomResize([280], max_size=504),#for r101`

or the default source code one:
`                     T.RandomResize([300], max_size=540),#for r50`

thanks in advance!!

**Comment by YuqingWang1029** [comment]
Hi @rambleramble, the result is achieved by the resolution of r101
