### ISSUE TITLE
Precomputed results?

### ISSUE THREAD

**Issue by hkchengrex** [Epiphqny/VisTR#6]
Thanks for the work!
Besides the pretrained model, can the precomputed results (jsons) also be made available?

I don't have access to a V100, and I would really appreciate having the precomputed results.
Thanks again!

**Comment by Epiphqny** [comment]
Hi @hkchengrex, I have uploaded the result json in the README, please check it out.

**Comment by hkchengrex** [comment]
Thanks a lot!

**Comment by Epiphqny** [comment]
@hkchengrex Please star it if it helps your research, thanks!
