### ISSUE TITLE
Code Request for Instance Matching

### ISSUE THREAD

**Issue by zyayoung** [Epiphqny/VisTR#65]
In section 4.2, the paper mentions:

> if the clip length is less than the video length, instance matching in overlapping frames is used for associating them from different clips.

Code for instance matching is crucial for running VisTR on GPUs with smaller VRAM. Could you kindly provide the corresponding code for this part? :smiley:

**Comment by YuqingWang1029** [comment]
Hi @zyayoung, please refer to https://github.com/Epiphqny/VisTR/blob/445c9e4e787a1fb3c959d7e7bb6ecf809bdac155/models/matcher.py#L49.
