### ISSUE TITLE
About the performance difference in different version of arxiv paper

### ISSUE THREAD

**Issue by Scalsol** [Epiphqny/VisTR#69]
Hi authors, thanks for this amazing work! I have some questions about the performance difference in different version of this paper on arxiv. In the first version, the performance of R-50 is 34.4, and in the final version, the performance is 36.2. Could you help explain what modification you make leads to this performance boost? Thanks!

**Comment by YuqingWang1029** [comment]
Hi @Scalsol, the difference is in data augmentation, https://github.com/Epiphqny/VisTR/blob/445c9e4e787a1fb3c959d7e7bb6ecf809bdac155/datasets/ytvos.py#L157

**Comment by Scalsol** [comment]
ok, thanks!
