### ISSUE TITLE
how to get visual result？

### ISSUE THREAD

**Issue by CuberrChen** [Epiphqny/VisTR#7]
can you provide the visual code？thanks. or how to covert the json file to visual image？

**Comment by Epiphqny** [comment]
Hi @CuberrChen, the visual code will not be provided, you could write it by decoding the masks.

**Comment by zhhezhhe** [comment]
I write some code to get mask back from rle. But some error occurs. How to convert rle to binary mask?
```
mask = (res_masks[n, m]).astype(np.uint8) 
rle = mask_util.encode(np.array(mask[:, :, np.newaxis], order='F'))[0]

rle["counts"] = rle["counts"].decode("utf-8")
a = rle["counts"].encode("utf-8")

mm = mask_util.decode(a)
```
Error:
```
return _mask.decode([rleObjs])[:,:,0]
  File "pycocotools/_mask.pyx", line 146, in pycocotools._mask.decode
  File "pycocotools/_mask.pyx", line 128, in pycocotools._mask._frString
TypeError: byte indices must be integers or slices, not str
```
Do you know how to visual the json   @CuberrChen

**Comment by qzsrh** [comment]
> can you provide the visual code？thanks. or how to covert the json file to visual image？

Hello! Have you addressed it? I met the same problem.
